version: '3'

services:
  database-mysql:
    container_name: commerce-database
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'commerce'
      TZ: Asia/Seoul

    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

    ports:
      - '3307:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'


  redis:
    container_name: commerce-redis
    image: redis:latest
    ports:
      - '6379:6379'