version: '3'

services:
  database-mysql:
    container_name: commerce-database
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'commerce'
      TZ: Asia/Seoul

    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

    ports:
      - '3307:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

#  database-adminer:
#    container_name: commerce-adminer
#    image: adminer:latest
#    ports:
#      - "18080:8080"
#    environment:
#      - ADMINER_DEFAULT_SERVER=database-mysql
#      - ADMINER_DESIGN=hydra
#      - ADMINER_PLUGINS=tables-filter tinymce